all:
	@echo 'DIGITAR:    #use "carregador.ml";;'
	rlwrap ocaml

compile:
	@echo "Vamos compilar o programa"
	@echo "ocamllex lexico.mll"
	ocamllex lexico.mll

	@echo "Vamos gerar o modelo do programa compilado"
	@echo "ocamlc -c lexico.ml"
	ocamlc -c lexico.ml

